version: '3.9'
services:
  uul-server:
    container_name: uul-server-dev
    build:
      context: ./server
    command: yarn start-dev
    volumes:
      - ./server:/app
      - /app/node_modules
    ports:
      - 5000:5000
    restart: always
    env_file: ./.env.dev
  uul-client:
    container_name: uul-client-dev
    build:
      context: ./client
    command: yarn start
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    depends_on:
      - uul-server
    restart: always
    ports:
      - 3000:3000
